code/tag: ''
dataloader/num_workers: 4
dataloader/pin_memory: true
device: NVIDIA A100-SXM4-40GB
dist/account_name: beknur.kalmakhanbet
dist/hostname: gpu-02
dist/jobid: '119261'
dist/nodes: 1
dist/world_size: 4
hp:
  datasets:
    train:
      collators:
        '0':
          apply_mode: batch
          cutmix_alpha: 1.0
          cutmix_p: 0.5
          kind: mix_collator
          lamb_mode: batch
          mixup_alpha: 0.8
          mixup_p: 0.5
          shuffle_mode: flip
      kind: imagenet1k
      sample_wrappers:
        '0':
          kind: x_transform_wrapper
          transform:
          - interpolation: bicubic
            kind: random_resized_crop
            scale:
            - 0.08
            - 1.0
            size: 192
          - kind: random_horizontal_flip
          - blur_sigma:
            - 0.1
            - 2.0
            kind: transforms.three_augment
          - brightness: 0.3
            contrast: 0.3
            hue: 0.0
            kind: color_jitter
            saturation: 0.3
          - kind: imagenet1k_norm
        '1':
          kind: one_hot_wrapper
      split: train
    val:
      kind: imagenet1k
      sample_wrappers:
        '0':
          kind: x_transform_wrapper
          transform:
          - interpolation: bicubic
            kind: resize
            size: 192
          - kind: center_crop
            size: 192
          - kind: imagenet1k_norm
      split: val
  master_factory_base_path: vislstm
  model:
    alternation: bidirectional
    bias: true
    bidirectional: false
    conv1d_kernel_size: 3
    depth: 24
    dim: 768
    drop_path_decay: false
    drop_path_rate: 0.2
    kind: models.single.vislstm
    mode: classifier
    optim:
      betas:
        '0': 0.9
        '1': 0.999
      clip_grad_norm: 1.0
      kind: adamw
      lr: 0.001
      lr_scaler:
        divisor: 1024
        kind: linear_lr_scaler
      schedule:
        end_value: 1.0e-06
        kind: linear_warmup_cosine_decay_schedule
        warmup_epochs: 5
      weight_decay: 0.05
    patch_size: 16
    pooling:
      aggregate: flatten
      kind: bilateral
    pos_embed_mode: learnable
    use_conv2d: true
  name: in1k-lstm-80m16-e400res192-bialter-bilatflat-lr1e3-conv2d3-bias
  stage_name: in1k
  trainer:
    backup_precision: float16
    callbacks:
      '0':
        kind: checkpoint_callback
      '1':
        every_n_epochs: 10
        kind: checkpoint_callback
        save_latest_optim: true
        save_latest_weights: true
        save_weights: false
      '2':
        dataset_key: val
        every_n_epochs: 1
        kind: offline_accuracy_callback
    effective_batch_size: 512
    kind: classification_trainer
    log_every_n_epochs: 1
    max_epochs: 400
    precision: bfloat16
    use_torch_compile: true
run_name: minLSTM
stage_name: in1k
trainer/accumulation_steps: 1
trainer/batch_size: 128
